version: "3.1"
services:
    mysql:
        build: docker/mysql
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "training_php"
        volumes:
            - ./docker/mysql_data:/var/lib/mysql
        restart: always
        networks:
            - training_php_network

    webserver:
        image: nginx:alpine
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
            - ./docker/nginx:/etc/nginx/conf.d
        ports:
            - "80:80"
        networks:
            - training_php_network

    php-fpm:
        build: docker/php-fpm
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
            - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini
        networks:
            - training_php_network

    queue:
        build: docker/php-fpm
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        command: php artisan queue:work
        networks:
            - training_php_network

    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
        networks:
            - training_php_network

    websocket:
        image: beyondcode/laravel-websockets
        environment:
            - BROADCAST_DRIVER=pusher
            - PUSHER_APP_ID=1807120
            - PUSHER_APP_KEY=ec2dde97d12e43be00da
            - PUSHER_APP_SECRET=4d509e87c04229f262bc
            - PUSHER_APP_CLUSTER=ap1
        networks:
            - training_php_network
        ports:
            - "6001:6001"

networks:
    training_php_network:
        driver: bridge
